### ISSUE TITLE
Minor package.json file could simplify Set up instructions

### ISSUE THREAD

**Issue by HyperSprite** [zeemee/react-firebase-example#2]
Thanks for the informative Meetup, these are much appreciated. I know this is just a sample repo, not sure if you are planning on using it in the future but figured I would throw this out there:

If you added the following to your package.json "devDependencies":
```json
    "webpack-dev-server": "^2.1.0-beta.12" 
```

and the following in your package.json "scripts":
```json
    "dev": "node_modules/webpack-dev-server/bin/webpack-dev-server.js"
```

Then the "Set up" section would be:

1. npm i
2. npm run dev
3. In your browser, go to localhost:8080

This would also reduce polluting the global npm space with installs attendees may or may not use again.

**Comment by alekhurst** [comment]
This is a great idea! Just merged it in. Thanks!
